name: 'TIL Auto-Format README'
description: 'A GitHub action that can be used with a TIL repo to autogenerate a README.md.'
author: 'Casey Flynn <cflynn07>'
icon: 'align-left'
color: 'purple'
inputs:
  description:
    description: 'Description text block featured at the top of your README.md'
    required: false
    default: ''
  footer:
    description: 'Footer text block, can be used for things like markdown links'
    required: false
    default: ''
  list_most_recent:
    description: 'List most recent n TILs in section below description'
    required: false
    default: '0'
  date_format:
    required: false
    description: 'Date format visible on list of most recent TILs. Must follow Go time format guidelines'
    default: '02 Jan 06 15:04 MST'
runs:
  using: 'docker'
  image: 'Dockerfile'
