FROM golang:1.14 as builder
WORKDIR /go/src/app
COPY . .
RUN go build -mod=vendor -o /go/bin/main .

FROM alpine:latest
WORKDIR /root
RUN apk update && apk add git
COPY --from=builder /go/bin/main ./main 
COPY --from=builder /go/src/app/README.md.tmpl ./README.md.tmpl
ENTRYPOINT [ "/root/entrypoint.sh" ]
